namespace AlloySample.Plugins
{
    public static class ListOfAnimals
    {
        public static string[] Animals = {
            "Aardvark",
            "Abyssinian",
            "Adelie Penguin",
            "Affenpinscher",
            "Afghan Hound",
            "African Bullfrog",
            "African Bush Elephant",
            "African Civet",
            "African Clawed Frog",
            "African Forest Elephant",
            "African Palm Civet",
            "African Penguin",
            "African Tree Toad",
            "African Wild Dog",
            "Ainu",
            "Baboon",
            "Bactrian Camel",
            "Badger",
            "Baiji",
            "Balinese",
            "Banded Palm Civet",
            "Bandicoot",
            "Banjo Catfish",
            "Barb",
            "Barn Owl",
            "Barnacle",
            "Barracuda",
            "Barramundi Fish",
            "Barred Owl",
            "Basenji Dog",
            "Basking Shark",
            "Bassador",
            "Basset Fauve de Bretagne",
            "Basset Hound",
            "Bassetoodle",
            "Bat",
            "Bavarian Mountain Hound",
            "Bea-Tzu",
            "Beabull",
            "Beagador",
            "Beagle",
            "Beagle Shepherd",
            "Caiman",
            "Caiman Lizard",
            "Cairn Terrier",
            "Camel",
            "Camel Cricket",
            "Camel Spider",
            "Canaan Dog",
            "Canada Lynx",
            "Canadian Eskimo Dog",
            "Canadian Horse",
            "Cane Corso",
            "Capybara",
            "Caracal",
            "Carolina Dog",
            "Carolina Parakeet",
            "Carp",
            "Cashmere Goat",
            "Cassowary",
            "Cat",
            "Caterpillar",
            "Catfish",
            "Dachsador",
            "Dachshund",
            "Dalmadoodle",
            "Dalmador",
            "Dalmatian",
            "Dapple Dachshund",
            "Darwin’s Frog",
            "Deer",
            "Deer Head Chihuahua",
            "Desert Locust",
            "Desert Rain Frog",
            "Desert Tortoise",
            "Deutsche Bracke",
            "Dhole",
            "Dingo",
            "Discus",
            "Doberman Pinscher",
            "Dodo",
            "Eagle",
            "Earwig",
            "Eastern Bluebird",
            "Eastern Gorilla",
            "Eastern Lowland Gorilla",
            "Eastern Phoebe",
            "Echidna",
            "Edible Frog",
            "Eel",
            "Egyptian Mau",
            "Electric Eel",
            "Elephant",
            "Elephant Seal",
            "Elephant Shrew",
            "Elk",
            "Falcon",
            "Fallow deer",
            "False Killer Whale",
            "Fangtooth",
            "Feist",
            "Fennec Fox",
            "Ferret",
            "Ferruginous Hawk",
            "Field Spaniel",
            "Fin Whale",
            "Finnish Spitz",
            "Fire salamander",
            "Fire-Bellied Toad",
            "Fish",
            "Fisher Cat",
            "Galapagos Penguin",
            "Galapagos Tortoise",
            "Gar",
            "Gecko",
            "Gentoo Penguin",
            "Geoffroys Tamarin",
            "Gerberian Shepsky",
            "Gerbil",
            "German Pinscher",
            "German Shepherd Guide",
            "German Sheppit",
            "German Sheprador",
            "Gharial",
            "Giant African Land Snail",
            "Giant Armadillo",
            "Giant Clam",
            "Giant Panda Bear",
            "Giant Salamander",
            "Giant Schnauzer",
            "Giant Schnoodle",
            "Gibbon",
            "Gila Monster",
            "Giraffe",
            "Glass Frog",
            "Hagfish",
            "Hammerhead Shark",
            "Hamster",
            "Harbor Seal",
            "Hare",
            "Harpy Eagle",
            "Harrier",
            "Havanese",
            "Havapoo",
            "Havashire",
            "Hawaiian Crow",
            "Hedgehog",
            "Hercules Beetle",
            "Hermit Crab",
            "Heron",
            "Herring",
            "Highland Cattle",
            "Himalayan",
            "Ibex",
            "Ibis",
            "Ibizan Hound",
            "Iguana",
            "Immortal Jellyfish",
            "Impala",
            "Indian Elephant",
            "Indian Giant Squirrel",
            "Indian Palm Squirrel",
            "Indian Rhinoceros",
            "Indian Star Tortoise",
            "Indochinese Tiger",
            "Indri",
            "Insects",
            "Irish Doodle",
            "Irish Setter",
            "Irish Terrier",
            "Irish WolfHound",
            "Italian Greyhound",
            "Ivory-billed woodpecker",
            "Jack Russell",
            "Jackabee",
            "Jackal",
            "Jaguar",
            "Japanese Chin",
            "Japanese Macaque",
            "Japanese Squirrel",
            "Japanese Terrier",
            "Javan Rhinoceros",
            "Javanese",
            "Jellyfish",
            "Jerboa",
            "Kakapo",
            "Kangaroo",
            "Kangaroo Rat",
            "Keel-Billed Toucan",
            "Keeshond",
            "Kerry Blue Terrier",
            "Killer Whale",
            "King Cobra",
            "King Crab",
            "King Penguin",
            "Kingfisher",
            "Kinkajou",
            "Kiwi",
            "Koala",
            "Komodo Dragon",
            "Kooikerhondje",
            "Kookaburra",
            "Koolie",
            "Krill",
            "Kudu",
            "Labmaraner",
            "Labradane",
            "Labradoodle",
            "Labrador Retriever",
            "Labraheeler",
            "Ladybug",
            "Lakeland Terrier",
            "Lamprey",
            "Leaf-Tailed Gecko",
            "Lemming",
            "Lemur",
            "Leopard",
            "Leopard Cat",
            "Leopard Frog",
            "Leopard Seal",
            "Leopard Tortoise",
            "Lhasapoo",
            "Liger",
            "Lion",
            "Lionfish",
            "Little Brown Bat",
            "Little Penguin",
            "Lizard",
            "Llama",
            "Loach",
            "Lobster",
            "Locust",
            "Long-Eared Owl",
            "Longnose Gar",
            "Lorikeet",
            "Lungfish",
            "Lynx",
            "Macaroni Penguin",
            "Macaw",
            "Magellanic Penguin",
            "Magpie",
            "Maine Coon",
            "Malayan Civet",
            "Malayan Tiger",
            "Malteagle",
            "Maltese",
            "Maltipoo",
            "Manatee",
            "Manchester Terrier",
            "Mandrill",
            "Maned Wolf",
            "Manta Ray",
            "Marble Fox",
            "Marine Iguana",
            "Marine Toad",
            "Markhor",
            "Marmot",
            "Marsh Frog",
            "Masked Palm Civet",
            "Mastador",
            "Mastiff",
            "Mayfly",
            "Meagle",
            "Meerkat",
            "Megalodon",
            "Mexican Alligator Lizard",
            "Mexican Free-Tailed Bat",
            "Milkfish",
            "Millipede",
            "Mini Labradoodle",
            "Miniature Bull Terrier",
            "Mink",
            "Minke Whale",
            "Mole",
            "Molly",
            "Monarch Butterfly",
            "Mongoose",
            "Mongrel",
            "Monitor Lizard",
            "Monkey",
            "Monkfish",
            "Monte Iberia Eleuth",
            "Moorhen",
            "Moose",
            "Moray Eel",
            "Morkie",
            "Moth",
            "Mountain Bluebird",
            "Mountain Cur",
            "Mountain Feist",
            "Mountain Gorilla",
            "Mountain Lion",
            "Mourning Dove",
            "Mouse",
            "Mudpuppy",
            "Mule",
            "Muskox",
            "Muskrat",
            "Myna Bird",
            "Naked Mole Rat",
            "Narwhal",
            "Neanderthal",
            "Neapolitan Mastiff",
            "Newfoundland",
            "Newfypoo",
            "Newt",
            "Nigerian Goat",
            "Nightingale",
            "Nile Crocodile",
            "No See Ums",
            "Norfolk Terrier",
            "North American Black Bear",
            "Northern Inuit Dog",
            "Norwegian Forest",
            "Norwich Terrier",
            "Numbat",
            "Nurse Shark",
            "Ocelot",
            "Octopus",
            "Okapi",
            "Old English Sheepdog",
            "Olm",
            "Opossum",
            "Orang-utan",
            "Ostrich",
            "Otter",
            "Oyster",
            "Paddlefish",
            "Pademelon",
            "Painted Turtle",
            "Pangolin",
            "Panther",
            "Parrot",
            "Parson Russell Terrier",
            "Patas Monkey",
            "Patterdale Terrier",
            "Peacock",
            "Peagle",
            "Peekapoo",
            "Pekingese",
            "Pelican",
            "Penguin",
            "Pere Davids Deer",
            "Peregrine Falcon",
            "Persian",
            "Petit Basset Griffon Vendéen",
            "Petite Goldendoodle",
            "Pheasant",
            "Pied Tamarin",
            "Pig",
            "Pigeon",
            "Pika",
            "Pike Fish",
            "Pileated Woodpecker",
            "Pink Fairy Armadillo",
            "Piranha",
            "Pitador",
            "Pitsky",
            "Platypus",
            "Pointer",
            "Poison Dart Frog",
            "Polar Bear",
            "Pomapoo",
            "Quail",
            "Quetzal",
            "Quokka",
            "Quoll",
            "Rabbit",
            "Raccoon",
            "Raccoon Dog",
            "Radiated Tortoise",
            "Ragdoll",
            "Raggle",
            "Rat",
            "Rat Terrier",
            "Rattlesnake",
            "Red Finch",
            "Red Fox",
            "Red Knee Tarantula",
            "Red Panda",
            "Red Squirrel",
            "Red Wolf",
            "Red-handed Tamarin",
            "Reindeer",
            "Rhinoceros",
            "River Turtle",
            "Robin",
            "Rock Hyrax",
            "Rockfish",
            "Rockhopper Penguin",
            "Rose-breasted Grosbeak",
            "Roseate Spoonbill",
            "Rottsky",
            "Rottweiler",
            "Royal Penguin",
            "Russell Terrier",
            "Russian Bear Dog",
            "Russian Blue",
            "Saarloos Wolfdog",
            "Saber-Toothed Tiger",
            "Sable",
            "Saiga",
            "Saint Berdoodle",
            "Saint Bernard",
            "Saint Shepherd",
            "Salamander",
            "Salmon",
            "Samoyed",
            "Sand Lizard",
            "Saola",
            "Sardines",
            "Sawfish",
            "Scarlet Macaw",
            "Schneagle",
            "Schnoodle",
            "Scimitar-horned Oryx",
            "Scorpion",
            "Scorpion Fish",
            "Scottish Terrier",
            "Sea Dragon",
            "Sea Lion",
            "Sea Otter",
            "Taco Terrier",
            "Tamaskan",
            "Tang",
            "Tapanuli Orang-utan",
            "Tapir",
            "Tarpon",
            "Tarsier",
            "Tasmanian Devil",
            "Tasmanian Tiger",
            "Tawny Owl",
            "Teddy Roosevelt Terrier",
            "Tenterfield Terrier",
            "Termite",
            "Terrier",
            "Tetra",
            "Thai Ridgeback",
            "Thorny Devil",
            "Tibetan Fox",
            "Tibetan Mastiff",
            "Tibetan Terrier",
            "Tiffany",
            "Tiger",
            "Tiger Salamander",
            "Tiger Shark",
            "Toadfish",
            "Torkie",
            "Tortoise",
            "Toucan",
            "Toy Fox Terrier",
            "Toy Poodle",
            "Tree Frog",
            "Tree Kangaroo",
            "Tree swallow",
            "Tropicbird",
            "Tsetse Fly",
            "Tuatara",
            "Tuna",
            "Turkey",
            "Turkish Angora",
            "Uakari",
            "Uguisu",
            "Umbrellabird",
            "Utonagan",
            "Vampire Bat",
            "Vampire Squid",
            "Vaquita",
            "Vervet Monkey",
            "Vulture",
            "Wallaby",
            "Walleye Fish",
            "Walrus",
            "Wandering Albatross",
            "Warthog",
            "Wasp",
            "Water Buffalo",
            "Water Dragon",
            "Water Vole",
            "Weasel",
            "Weimardoodle",
            "Welsh Corgi",
            "Welsh Terrier",
            "West Highland Terrier",
            "Western Gorilla",
            "Western Lowland Gorilla",
            "Westiepoo",
            "Whale Shark",
            "Wheaten Terrier",
            "Whippet",
            "White Rhinoceros",
            "White Tiger",
            "White-Faced Capuchin",
            "White-tail deer",
            "Whoodle",
            "Whooping Crane",
            "Wild Boar",
            "Wildebeest",
            "Wire Fox Terrier",
            "Wolf",
            "Wolf Eel",
            "Wolf Spider",
            "Wolffish",
            "Wolverine",
            "Wombat",
            "Wood Bison",
            "Wood Frog",
            "Wood Turtle",
            "Woodlouse",
            "Woodpecker",
            "Woolly Mammoth",
            "Woolly Monkey",
            "Wrasse",
            "Wyoming Toad",
            "X-Ray Tetra",
            "Xerus",
            "Xoloitzcuintli",
            "Yak",
            "Yakutian Laika",
            "Yellow Sac Spider",
            "Yellow-Eyed Penguin",
            "Yellowfin Tuna",
            "Yeti Crab",
            "Yoranian",
            "Yorkie Bichon",
            "Yorkie Poo",
            "Yorkshire Terrier",
            "Zebra",
            "Zebra Finch",
            "Zebra Mussels",
            "Zebra Pleco",
            "Zebra Shark",
            "Zebu",
            "Zonkey",
            "Zorse",
            "Zuchon"
        };
    }
}